## 作業目標：運用scikit-learn API 實現K-fold分割資料

---

### 讀入資料

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os

# Current directory
print(os.getcwd())

# change directory
os.chdir('/content/drive/MyDrive/python_training/NLP100Days/day_19-KNN-2/')
print(os.getcwd())

/content
/content/drive/MyDrive/python_training/NLP100Days/day_19-KNN-2


In [3]:
import pandas as pd
dataset = pd.read_csv(r'Social_Network_Ads.csv')

In [4]:
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

### 取出訓練特徵與標註

In [5]:
X = dataset[['User ID', 'Gender', 'Age', 'EstimatedSalary']].values
Y = dataset['Purchased'].values

In [6]:
X[0:5]

array([[15624510, 'Male', 19.0, 19000.0],
       [15810944, 'Male', 35.0, 20000.0],
       [15668575, 'Female', 26.0, 43000.0],
       [15603246, 'Female', 27.0, 57000.0],
       [15804002, 'Male', 19.0, 76000.0]], dtype=object)

In [7]:
Y[0:5]

array([0, 0, 0, 0, 0])

---

In [11]:
import numpy as np
from sklearn.model_selection import KFold

### 將訓練資料按照順序切割成10等分

In [12]:
kf = KFold(n_splits=10, shuffle=False, random_state=None)
#kf = KFold("自行填入")

kf.get_n_splits(X)

print(kf)


KFold(n_splits=10, random_state=None, shuffle=False)


### 將訓練資料隨機切割成10等分

In [13]:
kf = KFold(n_splits=10, shuffle=True, random_state=None)
#kf = KFold("自行填入")
kf.get_n_splits(X)

print(kf)

KFold(n_splits=10, random_state=None, shuffle=True)


---

### 取出 切割資料對應位置

In [14]:
train_split = kf.split(X)
next(train_split)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  64,  65,  66,
         67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  78,  79,  80,
         81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  93,  94,
         95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 108, 109,
        110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 122, 123,
        124, 125, 126, 127, 128, 129, 130, 132, 133, 134, 135, 136, 137,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 152,
        154, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 182,
        183, 184, 185, 186, 187, 188, 189, 190, 191

### Or

In [15]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [  0   2   3   4   5   6   7   8   9  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  26  27  28  29  30  31  32  34  35  36  37  38  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  57  58  59
  60  61  62  64  65  66  67  68  69  70  71  72  73  74  76  77  79  81
  83  84  86  87  88  89  90  91  92  95  96  97  98  99 100 101 102 103
 104 105 106 107 109 110 111 112 113 114 115 116 117 118 120 121 122 123
 124 125 126 127 128 130 131 132 133 134 135 136 137 138 139 140 141 142
 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 180
 181 182 183 184 185 186 187 188 189 190 192 193 194 195 196 197 199 200
 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218
 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236
 237 238 239 240 241 242 243 244 245 246 247 248 250 252 253 254 255 256
 257 258 259 260 261 262 263 264 265 266 267

In [16]:
train_index.shape

(360,)

In [17]:
test_index.shape

(40,)

### 取出切割資料：trainset / testset 特徵(x_train/x_test)/標註(y_train/y_test)

In [37]:
kf_dataset=[]
X_train_dataset=[]
Y_train_dataset=[]
X_test_dataset=[]
Y_test_dataset=[]
for train_index, test_index in kf.split(X):
  kf_dataset.append((train_index, test_index))
  X_train_dataset.append(X[train_index])
  X_test_dataset.append(X[test_index])
  Y_train_dataset.append(Y[train_index])
  Y_test_dataset.append(Y[test_index])
  #X_train, X_test = X[train_index], X[test_index]
  #y_train, y_test = y[train_index], y[test_index]

In [38]:
kf_dataset[0]

(array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  12,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  39,  40,  42,  43,
         44,  46,  47,  48,  49,  50,  51,  52,  54,  55,  56,  58,  59,
         60,  61,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  79,  80,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 110, 111, 112, 113, 114, 116,
        117, 119, 120, 121, 122, 123, 124, 126, 127, 128, 129, 130, 131,
        132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 145,
        146, 147, 148, 151, 152, 153, 154, 155, 156, 157, 159, 160, 161,
        163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 176,
        177, 178, 179, 180, 181, 182, 183, 186, 187, 188, 189, 190, 191,
        192, 193, 194, 195, 196, 197, 198, 199, 200

In [40]:
X_train_dataset[0]

array([[15810944, 'Male', 35.0, 20000.0],
       [15668575, 'Female', 26.0, 43000.0],
       [15603246, 'Female', 27.0, 57000.0],
       ...,
       [15654296, 'Female', 50.0, 20000.0],
       [15755018, 'Male', 36.0, 33000.0],
       [15594041, 'Female', 49.0, 36000.0]], dtype=object)

In [41]:
Y_train_dataset[0]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,